### ISSUE TITLE
Write an epic story for out game

### ISSUE THREAD

**Issue by Pepi100** [Pepi100/Duck-Adventures#35]

**Comment by iosoicristiana** [comment]
Our game's protagonist is a brave and courageous duck living on a peaceful island... until her eggs are stolen by a malicious vulture. Now she's on a mission to recover them.
	She has to complete challenges on her way so that she can get closer to her kids. There will be three challenges, each consisting of mini-games that test the duck's skills and abilities. She has to avoid all kinds of dangerous obstacles in various environments. Every win will give her advantages in the final fight. The last challenge will be to take down the vulture and reclaim her eggs so shhe can finally be happy with her family.
