### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by Pepi100** [Pepi100/Duck-Adventures#37]
An example for such a diagram can be found in [this](https://github.com/pizzandreea/Pufferfish-Game2.0) repo.

**Comment by DavidPatranjel** [comment]
![UML D A  (1)](https://user-images.githubusercontent.com/92601174/233869730-37f06417-ea6b-4222-b8b5-6917cbb57098.png)

**Comment by DavidPatranjel** [comment]
aici e o varianta de state diagram... parere?
